package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, ADD, ASK_GET, TELL_GET, POISON, TOKEN, RELEASE_MUTEX, COMMIT, REMOVE, QUIT, GIVEMYFILES, GIVE_ACCEPTED,
	SET_PRED
}
